export const MASTER_CATEGORIES = [
  {
    categoryId: "biscuits-cookies",
    name: "Biscuits & Cookies",
    iconName: "Cookie",
    displayOrder: 1,
    description: "Glucose biscuits, butter cookies, cream biscuits, rusks and wafers",
  },
  {
    categoryId: "snacks-namkeen",
    name: "Snacks & Namkeen",
    iconName: "Flame",
    displayOrder: 2,
    description: "Potato chips, bhujia, sev, mixtures, puffs, nachos and traditional savouries",
  },
  {
    categoryId: "chocolates-candies",
    name: "Chocolates & Candies",
    iconName: "Heart",
    displayOrder: 3,
    description: "Milk chocolates, wafer bars, dark chocolates, toffees and mint candies",
  },
  {
    categoryId: "noodles-pasta",
    name: "Noodles & Pasta",
    iconName: "Soup",
    displayOrder: 4,
    description: "Instant noodles, cup noodles, macaroni, penne and Hakka noodles",
  },
  {
    categoryId: "rice-flour-grains",
    name: "Rice, Flour & Grains",
    iconName: "Wheat",
    displayOrder: 5,
    description: "Basmati rice, sona masoori, whole wheat chakki atta, maida, sooji and poha",
  },
  {
    categoryId: "pulses-lentils",
    name: "Pulses & Lentils",
    iconName: "Boxes",
    displayOrder: 6,
    description: "Toor dal, moong dal, chana dal, urad dal, rajma, kabuli chana and masoor dal",
  },
  {
    categoryId: "edible-oils-ghee",
    name: "Edible Oils & Ghee",
    iconName: "Droplet",
    displayOrder: 7,
    description: "Mustard oil, sunflower oil, groundnut oil, refined soyabean oil and pure cow ghee",
  },
  {
    categoryId: "spices-masalas",
    name: "Spices & Masalas",
    iconName: "Sparkles",
    displayOrder: 8,
    description: "Turmeric, red chilli powder, coriander, garam masala, sabji masala and whole spices",
  },
  {
    categoryId: "tea-coffee",
    name: "Tea & Coffee",
    iconName: "Coffee",
    displayOrder: 9,
    description: "CTC leaf tea, green tea, masala chai bags, instant coffee and filter coffee blends",
  },
  {
    categoryId: "dairy-products",
    name: "Dairy Products",
    iconName: "Milk",
    displayOrder: 10,
    description: "Pasteurised pouch milk, table butter, cheese slices, paneer blocks and curd",
  },
  {
    categoryId: "beverages-juices",
    name: "Beverages & Juices",
    iconName: "Wine",
    displayOrder: 11,
    description: "Mineral water, carbonated soft drinks, fruit juices, energy drinks and squashes",
  },
  {
    categoryId: "bread-bakery",
    name: "Bread & Bakery",
    iconName: "Sandwich",
    displayOrder: 12,
    description: "White sandwich bread, brown bread, pav, burger buns, cakes and rusk toasts",
  },
  {
    categoryId: "personal-care",
    name: "Personal Care",
    iconName: "Smile",
    displayOrder: 13,
    description: "Bathing soaps, body wash, shampoos, toothpaste, toothbrushes and hair oils",
  },
  {
    categoryId: "home-cleaning",
    name: "Home Cleaning",
    iconName: "Sparkle",
    displayOrder: 14,
    description: "Detergent powder, detergent bars, dishwash liquids, floor cleaners and toilet cleaners",
  },
  {
    categoryId: "packaged-foods",
    name: "Packaged Foods",
    iconName: "PackageCheck",
    displayOrder: 15,
    description: "Tomato ketchup, mayonnaise, jams, honey, breakfast cereals and ready mixes",
  },
  {
    categoryId: "baby-care",
    name: "Baby Care",
    iconName: "Baby",
    displayOrder: 16,
    description: "Diapers, baby wipes, baby soap, gentle baby shampoo and infant nutrition",
  },
  {
    categoryId: "stationery",
    name: "Stationery",
    iconName: "PenTool",
    displayOrder: 17,
    description: "Ballpoint pens, gel pens, pencils, notebooks, erasers, sharpeners and adhesives",
  },
  {
    categoryId: "other-local-products",
    name: "Other / Local Products",
    iconName: "Store",
    displayOrder: 18,
    description: "Locally packed goods, regional specialties, artisanal provisions and misc items",
  },
];

export const MASTER_PRODUCTS = [
  // ==========================================
  // 1. BISCUITS & COOKIES (CAT-BIS)
  // ==========================================
  {
    productId: "CAT-BIS-001",
    name: "Parle-G Original Glucose Biscuits",
    brand: "Parle",
    categoryId: "biscuits-cookies",
    category: "Biscuits & Cookies",
    variant: "Original Glucose",
    packSize: "800g Super Saver",
    unit: "packet",
    barcode: "8901063012117",
    mrp: 80,
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&auto=format&fit=crop&q=80",
    description: "India's beloved glucose biscuits made with milk and wheat. Perfect tea-time companion.",
  },
  {
    productId: "CAT-BIS-002",
    name: "Parle-G Original Glucose Biscuit",
    brand: "Parle",
    categoryId: "biscuits-cookies",
    category: "Biscuits & Cookies",
    variant: "Original Glucose",
    packSize: "130g",
    unit: "packet",
    barcode: "8901063012100",
    mrp: 10,
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&auto=format&fit=crop&q=80",
    description: "Classic small pack of Parle-G glucose biscuits.",
  },
  {
    productId: "CAT-BIS-003",
    name: "Britannia Good Day Cashew Cookies",
    brand: "Britannia",
    categoryId: "biscuits-cookies",
    category: "Biscuits & Cookies",
    variant: "Rich Cashew",
    packSize: "200g",
    unit: "packet",
    barcode: "8901063140018",
    mrp: 45,
    imageUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=500&auto=format&fit=crop&q=80",
    description: "Delicious melt-in-mouth cookies loaded with real cashew nuts and rich aroma.",
  },
  {
    productId: "CAT-BIS-004",
    name: "Britannia Good Day Butter Cookies",
    brand: "Britannia",
    categoryId: "biscuits-cookies",
    category: "Biscuits & Cookies",
    variant: "Butter Delight",
    packSize: "200g",
    unit: "packet",
    barcode: "8901063140025",
    mrp: 40,
    imageUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=500&auto=format&fit=crop&q=80",
    description: "Crispy, rich butter cookies with iconic smile ridges.",
  },
  {
    productId: "CAT-BIS-005",
    name: "Britannia Marie Gold Biscuits",
    brand: "Britannia",
    categoryId: "biscuits-cookies",
    category: "Biscuits & Cookies",
    variant: "Classic Tea Biscuit",
    packSize: "250g",
    unit: "packet",
    barcode: "8901063110035",
    mrp: 35,
    imageUrl: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=500&auto=format&fit=crop&q=80",
    description: "Light and crisp tea-time biscuit with essential vitamins and zero trans fat.",
  },
  {
    productId: "CAT-BIS-006",
    name: "Britannia 50-50 Sweet & Salty",
    brand: "Britannia",
    categoryId: "biscuits-cookies",
    category: "Biscuits & Cookies",
    variant: "Sweet & Salty",
    packSize: "150g",
    unit: "packet",
    barcode: "8901063130057",
    mrp: 25,
    imageUrl: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=500&auto=format&fit=crop&q=80",
    description: "The classic cracker biscuit offering the twin joy of sweet and salty notes.",
  },
  {
    productId: "CAT-BIS-007",
    name: "Oreo Vanilla Creme Sandwich Biscuits",
    brand: "Cadbury Oreo",
    categoryId: "biscuits-cookies",
    category: "Biscuits & Cookies",
    variant: "Vanilla Creme",
    packSize: "120g",
    unit: "packet",
    barcode: "7622201726058",
    mrp: 35,
    imageUrl: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=500&auto=format&fit=crop&q=80",
    description: "Rich dark cocoa cookie shells sandwiching velvety vanilla creme. Twist, lick, dunk.",
  },
  {
    productId: "CAT-BIS-008",
    name: "Sunfeast Dark Fantasy Choco Fills",
    brand: "Sunfeast",
    categoryId: "biscuits-cookies",
    category: "Biscuits & Cookies",
    variant: "Choco Fills",
    packSize: "300g Party Pack",
    unit: "box",
    barcode: "8901725132216",
    mrp: 140,
    imageUrl: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=500&auto=format&fit=crop&q=80",
    description: "Crispy cookie crust filled with luscious molten molten chocolate core.",
  },
  {
    productId: "CAT-BIS-009",
    name: "Britannia Bourbon Chocolate Cream Biscuits",
    brand: "Britannia",
    categoryId: "biscuits-cookies",
    category: "Biscuits & Cookies",
    variant: "Chocolate Creme",
    packSize: "150g",
    unit: "packet",
    barcode: "8901063120010",
    mrp: 30,
    imageUrl: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=500&auto=format&fit=crop&q=80",
    description: "Original chocolate cream biscuits sprinkled with crunchy sugar crystals.",
  },
  {
    productId: "CAT-BIS-010",
    name: "Parle Monaco Salted Crackers",
    brand: "Parle",
    categoryId: "biscuits-cookies",
    category: "Biscuits & Cookies",
    variant: "Classic Salted",
    packSize: "200g",
    unit: "packet",
    barcode: "8901063022017",
    mrp: 30,
    imageUrl: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=500&auto=format&fit=crop&q=80",
    description: "Crispy light salted crackers, great with cheese spreads and toppings.",
  },
  {
    productId: "CAT-BIS-011",
    name: "Britannia NutriChoice Digestive Biscuits",
    brand: "Britannia",
    categoryId: "biscuits-cookies",
    category: "Biscuits & Cookies",
    variant: "Hi-Fibre Digestive",
    packSize: "250g",
    unit: "packet",
    barcode: "8901063150017",
    mrp: 50,
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&auto=format&fit=crop&q=80",
    description: "Wholesome digestive biscuits crafted with whole wheat and dietary fiber.",
  },
  {
    productId: "CAT-BIS-012",
    name: "Sunfeast Mom's Magic Cashew & Almond",
    brand: "Sunfeast",
    categoryId: "biscuits-cookies",
    category: "Biscuits & Cookies",
    variant: "Cashew & Almond",
    packSize: "200g",
    unit: "packet",
    barcode: "8901725132018",
    mrp: 40,
    imageUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=500&auto=format&fit=crop&q=80",
    description: "Buttery roasted cookies loaded with real cashew and roasted almond pieces.",
  },

  // ==========================================
  // 2. SNACKS & NAMKEEN (CAT-SNA)
  // ==========================================
  {
    productId: "CAT-SNA-001",
    name: "Lay's India's Magic Masala Potato Chips",
    brand: "Lay's",
    categoryId: "snacks-namkeen",
    category: "Snacks & Namkeen",
    variant: "India's Magic Masala",
    packSize: "50g",
    unit: "packet",
    barcode: "8901491101837",
    mrp: 20,
    imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80",
    description: "Crunchy sliced potato chips seasoned with aromatic Indian spices.",
  },
  {
    productId: "CAT-SNA-002",
    name: "Lay's American Style Cream & Onion",
    brand: "Lay's",
    categoryId: "snacks-namkeen",
    category: "Snacks & Namkeen",
    variant: "Cream & Onion",
    packSize: "50g",
    unit: "packet",
    barcode: "8901491101844",
    mrp: 20,
    imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80",
    description: "Thin cut potato crisps with smooth sour cream and onion herb seasoning.",
  },
  {
    productId: "CAT-SNA-003",
    name: "Lay's Classic Salted Potato Chips",
    brand: "Lay's",
    categoryId: "snacks-namkeen",
    category: "Snacks & Namkeen",
    variant: "Classic Salted",
    packSize: "50g",
    unit: "packet",
    barcode: "8901491101851",
    mrp: 20,
    imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80",
    description: "Golden fried sliced potatoes dusted with refined rock salt.",
  },
  {
    productId: "CAT-SNA-004",
    name: "Kurkure Masala Munch Crispy Snack",
    brand: "Kurkure",
    categoryId: "snacks-namkeen",
    category: "Snacks & Namkeen",
    variant: "Masala Munch",
    packSize: "82g",
    unit: "packet",
    barcode: "8901491001014",
    mrp: 20,
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3d5d62816dd?w=500&auto=format&fit=crop&q=80",
    description: "Tedhe-medhe crispy corn puffs bursting with tangy spices.",
  },
  {
    productId: "CAT-SNA-005",
    name: "Kurkure Green Chutney Style",
    brand: "Kurkure",
    categoryId: "snacks-namkeen",
    category: "Snacks & Namkeen",
    variant: "Green Chutney",
    packSize: "75g",
    unit: "packet",
    barcode: "8901491001021",
    mrp: 20,
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3d5d62816dd?w=500&auto=format&fit=crop&q=80",
    description: "Zesty green coriander and mint chutney flavoured corn twists.",
  },
  {
    productId: "CAT-SNA-006",
    name: "Bingo! Tedhe Medhe Masala Tadka",
    brand: "Bingo!",
    categoryId: "snacks-namkeen",
    category: "Snacks & Namkeen",
    variant: "Masala Tadka",
    packSize: "90g",
    unit: "packet",
    barcode: "8901725114014",
    mrp: 20,
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3d5d62816dd?w=500&auto=format&fit=crop&q=80",
    description: "Spindle shaped spindle sticks with punchy achaar masala flavour.",
  },
  {
    productId: "CAT-SNA-007",
    name: "Haldiram's Nagpur Aloo Bhujia",
    brand: "Haldiram's",
    categoryId: "snacks-namkeen",
    category: "Snacks & Namkeen",
    variant: "Aloo Bhujia",
    packSize: "400g Pouch",
    unit: "packet",
    barcode: "8904004400125",
    mrp: 110,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80",
    description: "Crunchy potato and gram flour crispy vermicelli seasoned with mint and spices.",
  },
  {
    productId: "CAT-SNA-008",
    name: "Haldiram's Nagpur Bhujia Sev",
    brand: "Haldiram's",
    categoryId: "snacks-namkeen",
    category: "Snacks & Namkeen",
    variant: "Bhujia Sev",
    packSize: "400g Pouch",
    unit: "packet",
    barcode: "8904004400118",
    mrp: 105,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80",
    description: "Traditional spicy Bikaneri sev made from moth bean flour and aromatic spices.",
  },
  {
    productId: "CAT-SNA-009",
    name: "Haldiram's Khatta Meetha Mixture",
    brand: "Haldiram's",
    categoryId: "snacks-namkeen",
    category: "Snacks & Namkeen",
    variant: "Khatta Meetha",
    packSize: "400g Pouch",
    unit: "packet",
    barcode: "8904004400132",
    mrp: 100,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80",
    description: "Sweet and sour mixture of puffed rice, sev, sago and roasted peanuts.",
  },
  {
    productId: "CAT-SNA-010",
    name: "Haldiram's Moong Dal Namkeen",
    brand: "Haldiram's",
    categoryId: "snacks-namkeen",
    category: "Snacks & Namkeen",
    variant: "Salted Moong Dal",
    packSize: "200g",
    unit: "packet",
    barcode: "8904004400149",
    mrp: 60,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80",
    description: "Crispy salted yellow moong pulses fried to golden perfection.",
  },
  {
    productId: "CAT-SNA-011",
    name: "Balaji Wafers Masala Wafers",
    brand: "Balaji",
    categoryId: "snacks-namkeen",
    category: "Snacks & Namkeen",
    variant: "Masala Wafers",
    packSize: "135g Party Pack",
    unit: "packet",
    barcode: "8906010500115",
    mrp: 35,
    imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80",
    description: "Crisp potato chips with popular western Indian masala seasoning.",
  },

  // ==========================================
  // 3. CHOCOLATES & CANDIES (CAT-CHO)
  // ==========================================
  {
    productId: "CAT-CHO-001",
    name: "Cadbury Dairy Milk Chocolate Bar",
    brand: "Cadbury",
    categoryId: "chocolates-candies",
    category: "Chocolates & Candies",
    variant: "Dairy Milk",
    packSize: "50g",
    unit: "piece",
    barcode: "7622201700010",
    mrp: 45,
    imageUrl: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&auto=format&fit=crop&q=80",
    description: "Creamy, smooth milk chocolate crafted with pure fresh dairy goodness.",
  },
  {
    productId: "CAT-CHO-002",
    name: "Cadbury Dairy Milk Silk Chocolate",
    brand: "Cadbury",
    categoryId: "chocolates-candies",
    category: "Chocolates & Candies",
    variant: "Silk Classic",
    packSize: "60g",
    unit: "piece",
    barcode: "7622201700027",
    mrp: 85,
    imageUrl: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&auto=format&fit=crop&q=80",
    description: "Ultra smooth, velvety indulgence that melts in your mouth.",
  },
  {
    productId: "CAT-CHO-003",
    name: "Nestle KitKat 4 Finger Chocolate",
    brand: "Nestle",
    categoryId: "chocolates-candies",
    category: "Chocolates & Candies",
    variant: "4 Finger Wafer",
    packSize: "38.5g",
    unit: "piece",
    barcode: "8901058852308",
    mrp: 30,
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&auto=format&fit=crop&q=80",
    description: "Crisp baked wafer fingers smothered in rich milk chocolate. Have a break.",
  },
  {
    productId: "CAT-CHO-004",
    name: "Nestle Munch Crunchy Wafer Bar",
    brand: "Nestle",
    categoryId: "chocolates-candies",
    category: "Chocolates & Candies",
    variant: "Crunchy Wafer",
    packSize: "21.6g",
    unit: "piece",
    barcode: "8901058852100",
    mrp: 10,
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&auto=format&fit=crop&q=80",
    description: "Crispy and light chocolate coated wafer bar with a crunchy bite.",
  },
  {
    productId: "CAT-CHO-005",
    name: "Cadbury 5 Star Chocolate Bar",
    brand: "Cadbury",
    categoryId: "chocolates-candies",
    category: "Chocolates & Candies",
    variant: "Caramel & Nougat",
    packSize: "40g",
    unit: "piece",
    barcode: "7622201700034",
    mrp: 20,
    imageUrl: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&auto=format&fit=crop&q=80",
    description: "Chewy golden caramel and nougat covered in rich Cadbury chocolate.",
  },
  {
    productId: "CAT-CHO-006",
    name: "Alpenliebe Gold Caramel Candy Toffee",
    brand: "Perfetti Van Melle",
    categoryId: "chocolates-candies",
    category: "Chocolates & Candies",
    variant: "Caramel Candy",
    packSize: "240g Pouch (60 units)",
    unit: "packet",
    barcode: "8902088011029",
    mrp: 50,
    imageUrl: "https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=500&auto=format&fit=crop&q=80",
    description: "Rich buttery caramel hard boiled candy beloved by all ages.",
  },
  {
    productId: "CAT-CHO-007",
    name: "Pulse Kachcha Aam Tangy Candy",
    brand: "Pass Pass",
    categoryId: "chocolates-candies",
    category: "Chocolates & Candies",
    variant: "Kachcha Aam",
    packSize: "200g Pouch",
    unit: "packet",
    barcode: "8901031123456",
    mrp: 50,
    imageUrl: "https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=500&auto=format&fit=crop&q=80",
    description: "Raw mango candy with an explosive tangy spicy masala center.",
  },

  // ==========================================
  // 4. NOODLES & PASTA (CAT-NOO)
  // ==========================================
  {
    productId: "CAT-NOO-001",
    name: "Maggi 2-Minute Masala Instant Noodles",
    brand: "Nestle Maggi",
    categoryId: "noodles-pasta",
    category: "Noodles & Pasta",
    variant: "Masala",
    packSize: "280g (4-Pack)",
    unit: "packet",
    barcode: "8901058857211",
    mrp: 56,
    imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80",
    description: "India's iconic instant noodles blended with authentic 10-spice tastemaker.",
  },
  {
    productId: "CAT-NOO-002",
    name: "Maggi 2-Minute Masala Single Pack",
    brand: "Nestle Maggi",
    categoryId: "noodles-pasta",
    category: "Noodles & Pasta",
    variant: "Masala",
    packSize: "70g",
    unit: "packet",
    barcode: "8901058857204",
    mrp: 14,
    imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80",
    description: "Single portion 70g instant noodles with aromatic masala seasoning.",
  },
  {
    productId: "CAT-NOO-003",
    name: "Sunfeast YiPPee! Magic Masala Noodles",
    brand: "Sunfeast YiPPee!",
    categoryId: "noodles-pasta",
    category: "Noodles & Pasta",
    variant: "Magic Masala",
    packSize: "240g (4-Pack)",
    unit: "packet",
    barcode: "8901725121012",
    mrp: 48,
    imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80",
    description: "Long, non-sticky round noodles infused with dehydrated vegetables and spices.",
  },
  {
    productId: "CAT-NOO-004",
    name: "Maggi Special Masala Noodles",
    brand: "Nestle Maggi",
    categoryId: "noodles-pasta",
    category: "Noodles & Pasta",
    variant: "Special Masala",
    packSize: "70g",
    unit: "packet",
    barcode: "8901058857242",
    mrp: 18,
    imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80",
    description: "Enriched with 20 whole spices and herbs for an extra aromatic kick.",
  },
  {
    productId: "CAT-NOO-005",
    name: "Bambino Macaroni Pasta",
    brand: "Bambino",
    categoryId: "noodles-pasta",
    category: "Noodles & Pasta",
    variant: "Durum Wheat Macaroni",
    packSize: "500g",
    unit: "packet",
    barcode: "8901416001013",
    mrp: 55,
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3d5d62816dd?w=500&auto=format&fit=crop&q=80",
    description: "100% durum wheat semolina elbow macaroni, rich in protein and non-sticky.",
  },
  {
    productId: "CAT-NOO-006",
    name: "Ching's Secret Hakka Noodles",
    brand: "Ching's Secret",
    categoryId: "noodles-pasta",
    category: "Noodles & Pasta",
    variant: "Veg Hakka Noodles",
    packSize: "150g",
    unit: "packet",
    barcode: "8901595851010",
    mrp: 35,
    imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80",
    description: "Authentic Desi Chinese long wheat noodles for quick chowmein cooking.",
  },

  // ==========================================
  // 5. RICE, FLOUR & GRAINS (CAT-RIC)
  // ==========================================
  {
    productId: "CAT-RIC-001",
    name: "Aashirvaad Shudh Chakki Whole Wheat Atta",
    brand: "Aashirvaad",
    categoryId: "rice-flour-grains",
    category: "Rice, Flour & Grains",
    variant: "100% Whole Wheat",
    packSize: "5kg Bag",
    unit: "packet",
    barcode: "8901725131011",
    mrp: 260,
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80",
    description: "Stone-ground chakki whole wheat flour retaining superior fiber and softness.",
  },
  {
    productId: "CAT-RIC-002",
    name: "Aashirvaad Shudh Chakki Whole Wheat Atta 10kg",
    brand: "Aashirvaad",
    categoryId: "rice-flour-grains",
    category: "Rice, Flour & Grains",
    variant: "100% Whole Wheat",
    packSize: "10kg Bag",
    unit: "packet",
    barcode: "8901725131028",
    mrp: 495,
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80",
    description: "Value family pack of premium chakki atta for soft, fluffy rotis.",
  },
  {
    productId: "CAT-RIC-003",
    name: "Fortune Chakki Fresh Whole Wheat Atta",
    brand: "Fortune",
    categoryId: "rice-flour-grains",
    category: "Rice, Flour & Grains",
    variant: "Chakki Fresh",
    packSize: "5kg Bag",
    unit: "packet",
    barcode: "8906007281010",
    mrp: 240,
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80",
    description: "Finely ground premium MP sharbati wheat flour delivering soft rotis.",
  },
  {
    productId: "CAT-RIC-004",
    name: "India Gate Basmati Rice Feast Rozzana",
    brand: "India Gate",
    categoryId: "rice-flour-grains",
    category: "Rice, Flour & Grains",
    variant: "Rozzana Daily",
    packSize: "5kg Bag",
    unit: "packet",
    barcode: "8901537001016",
    mrp: 475,
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80",
    description: "Aromatic aged long grain basmati rice ideal for everyday pulao and steamed rice.",
  },
  {
    productId: "CAT-RIC-005",
    name: "Daawat Rozana Gold Basmati Rice",
    brand: "Daawat",
    categoryId: "rice-flour-grains",
    category: "Rice, Flour & Grains",
    variant: "Rozana Gold",
    packSize: "5kg Bag",
    unit: "packet",
    barcode: "8901537002013",
    mrp: 450,
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80",
    description: "Finest medium-to-long grain basmati with sweet nutty aroma.",
  },
  {
    productId: "CAT-RIC-006",
    name: "Tata Sampann High Fibre Poha",
    brand: "Tata Sampann",
    categoryId: "rice-flour-grains",
    category: "Rice, Flour & Grains",
    variant: "Thick Poha",
    packSize: "500g",
    unit: "packet",
    barcode: "8901042961019",
    mrp: 55,
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80",
    description: "High quality flattened rice flakes rich in natural iron and dietary fiber.",
  },
  {
    productId: "CAT-RIC-007",
    name: "Rajdhani Sooji / Rawa",
    brand: "Rajdhani",
    categoryId: "rice-flour-grains",
    category: "Rice, Flour & Grains",
    variant: "Granulated Semolina",
    packSize: "500g",
    unit: "packet",
    barcode: "8906015501017",
    mrp: 40,
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80",
    description: "Hygienically sorted granular wheat semolina for halwa, upma, and idli batter.",
  },
  {
    productId: "CAT-RIC-008",
    name: "Rajdhani Maida Refined Wheat Flour",
    brand: "Rajdhani",
    categoryId: "rice-flour-grains",
    category: "Rice, Flour & Grains",
    variant: "Fine White Maida",
    packSize: "500g",
    unit: "packet",
    barcode: "8906015501024",
    mrp: 38,
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80",
    description: "Double filtered all-purpose wheat flour for parathas, samosas, and baking.",
  },

  // ==========================================
  // 6. PULSES & LENTILS (CAT-PUL)
  // ==========================================
  {
    productId: "CAT-PUL-001",
    name: "Tata Sampann Unpolished Toor Dal",
    brand: "Tata Sampann",
    categoryId: "pulses-lentils",
    category: "Pulses & Lentils",
    variant: "Unpolished Arhar / Toor",
    packSize: "1kg Pouch",
    unit: "packet",
    barcode: "8901042951010",
    mrp: 185,
    imageUrl: "https://images.unsplash.com/photo-1585849834908-3481231155e8?w=500&auto=format&fit=crop&q=80",
    description: "Naturally dried unpolished pigeon pea dal retaining natural nutrients and aroma.",
  },
  {
    productId: "CAT-PUL-002",
    name: "Tata Sampann Unpolished Moong Dal Yellow",
    brand: "Tata Sampann",
    categoryId: "pulses-lentils",
    category: "Pulses & Lentils",
    variant: "Moong Dhuli",
    packSize: "1kg Pouch",
    unit: "packet",
    barcode: "8901042951027",
    mrp: 165,
    imageUrl: "https://images.unsplash.com/photo-1585849834908-3481231155e8?w=500&auto=format&fit=crop&q=80",
    description: "High protein unpolished split skinless mung beans, easy to digest.",
  },
  {
    productId: "CAT-PUL-003",
    name: "Tata Sampann Unpolished Chana Dal",
    brand: "Tata Sampann",
    categoryId: "pulses-lentils",
    category: "Pulses & Lentils",
    variant: "Chana Dal",
    packSize: "1kg Pouch",
    unit: "packet",
    barcode: "8901042951034",
    mrp: 120,
    imageUrl: "https://images.unsplash.com/photo-1585849834908-3481231155e8?w=500&auto=format&fit=crop&q=80",
    description: "Unpolished Bengal gram dal loaded with protein and wholesome taste.",
  },
  {
    productId: "CAT-PUL-004",
    name: "Fortune Unpolished Urad Dal White Split",
    brand: "Fortune",
    categoryId: "pulses-lentils",
    category: "Pulses & Lentils",
    variant: "Urad Dhuli",
    packSize: "1kg Pouch",
    unit: "packet",
    barcode: "8906007282017",
    mrp: 170,
    imageUrl: "https://images.unsplash.com/photo-1585849834908-3481231155e8?w=500&auto=format&fit=crop&q=80",
    description: "Premium unpolished split white black gram, ideal for dosa and idli batter.",
  },
  {
    productId: "CAT-PUL-005",
    name: "Tata Sampann Chitra Rajma",
    brand: "Tata Sampann",
    categoryId: "pulses-lentils",
    category: "Pulses & Lentils",
    variant: "Chitra Kidney Beans",
    packSize: "1kg Pouch",
    unit: "packet",
    barcode: "8901042951041",
    mrp: 175,
    imageUrl: "https://images.unsplash.com/photo-1585849834908-3481231155e8?w=500&auto=format&fit=crop&q=80",
    description: "Soft cooking Himalayan Chitra red kidney beans for rich Punjabi curries.",
  },
  {
    productId: "CAT-PUL-006",
    name: "Fortune Kabuli Chana Premium",
    brand: "Fortune",
    categoryId: "pulses-lentils",
    category: "Pulses & Lentils",
    variant: "Large Chickpeas",
    packSize: "1kg Pouch",
    unit: "packet",
    barcode: "8906007282024",
    mrp: 160,
    imageUrl: "https://images.unsplash.com/photo-1585849834908-3481231155e8?w=500&auto=format&fit=crop&q=80",
    description: "Jumbo graded white chickpeas that cook soft and plump for chole bhature.",
  },

  // ==========================================
  // 7. EDIBLE OILS & GHEE (CAT-OIL)
  // ==========================================
  {
    productId: "CAT-OIL-001",
    name: "Fortune Sunlite Refined Sunflower Oil",
    brand: "Fortune",
    categoryId: "edible-oils-ghee",
    category: "Edible Oils & Ghee",
    variant: "Refined Sunflower",
    packSize: "1 Litre Pouch",
    unit: "pouch",
    barcode: "8906007283014",
    mrp: 145,
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80",
    description: "Light sunflower oil enriched with Vitamins A & D, heart-friendly and neutral taste.",
  },
  {
    productId: "CAT-OIL-002",
    name: "Fortune Kachi Ghani Pure Mustard Oil",
    brand: "Fortune",
    categoryId: "edible-oils-ghee",
    category: "Edible Oils & Ghee",
    variant: "Cold Pressed Mustard",
    packSize: "1 Litre Bottle",
    unit: "bottle",
    barcode: "8906007283021",
    mrp: 160,
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80",
    description: "Traditional cold-pressed pungent mustard oil for authentic pickles and curries.",
  },
  {
    productId: "CAT-OIL-003",
    name: "Saffola Gold Pro Healthy Lifestyle Oil",
    brand: "Saffola",
    categoryId: "edible-oils-ghee",
    category: "Edible Oils & Ghee",
    variant: "Blended Rice Bran & Sunflower",
    packSize: "1 Litre Pouch",
    unit: "pouch",
    barcode: "8901088011018",
    mrp: 175,
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80",
    description: "Dual seed technology with antioxidants that absorb up to 20% less oil.",
  },
  {
    productId: "CAT-OIL-004",
    name: "Amul Pure Cow Ghee Tin",
    brand: "Amul",
    categoryId: "edible-oils-ghee",
    category: "Edible Oils & Ghee",
    variant: "Pure Cow Ghee",
    packSize: "1 Litre Tin",
    unit: "tin",
    barcode: "8901262010107",
    mrp: 620,
    imageUrl: "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=500&auto=format&fit=crop&q=80",
    description: "Traditional granular golden cow ghee made from fresh cream with rich aroma.",
  },
  {
    productId: "CAT-OIL-005",
    name: "Amul Pure Ghee Pouch",
    brand: "Amul",
    categoryId: "edible-oils-ghee",
    category: "Edible Oils & Ghee",
    variant: "Pure Milk Ghee",
    packSize: "500ml Pouch",
    unit: "pouch",
    barcode: "8901262010114",
    mrp: 295,
    imageUrl: "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=500&auto=format&fit=crop&q=80",
    description: "Economical 500ml refill pouch of wholesome pure dairy ghee.",
  },

  // ==========================================
  // 8. SPICES & MASALAS (CAT-SPI)
  // ==========================================
  {
    productId: "CAT-SPI-001",
    name: "Tata Salt Vacuum Evaporated Iodised Salt",
    brand: "Tata Salt",
    categoryId: "spices-masalas",
    category: "Spices & Masalas",
    variant: "Iodised Table Salt",
    packSize: "1kg Pouch",
    unit: "packet",
    barcode: "8901042911014",
    mrp: 28,
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80",
    description: "Desh ka Namak. Pure vacuum evaporated iodised salt for mental and physical health.",
  },
  {
    productId: "CAT-SPI-002",
    name: "Everest Turmeric Powder (Haldi)",
    brand: "Everest",
    categoryId: "spices-masalas",
    category: "Spices & Masalas",
    variant: "Haldi Powder",
    packSize: "200g Box",
    unit: "box",
    barcode: "8901786101015",
    mrp: 65,
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80",
    description: "High curcumin golden yellow turmeric powder sourced from premier Salem fields.",
  },
  {
    productId: "CAT-SPI-003",
    name: "Everest Tikhalal Hot Red Chilli Powder",
    brand: "Everest",
    categoryId: "spices-masalas",
    category: "Spices & Masalas",
    variant: "Tikhalal Chilli",
    packSize: "200g Box",
    unit: "box",
    barcode: "8901786101022",
    mrp: 85,
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80",
    description: "Finely ground fiery red chillies giving vibrant color and spicy heat.",
  },
  {
    productId: "CAT-SPI-004",
    name: "Everest Coriander Powder (Dhaniya)",
    brand: "Everest",
    categoryId: "spices-masalas",
    category: "Spices & Masalas",
    variant: "Dhaniya Powder",
    packSize: "200g Box",
    unit: "box",
    barcode: "8901786101039",
    mrp: 60,
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80",
    description: "Freshly milled fragrant coriander seeds adding gentle sweetness to gravies.",
  },
  {
    productId: "CAT-SPI-005",
    name: "Everest Garam Masala Blend",
    brand: "Everest",
    categoryId: "spices-masalas",
    category: "Spices & Masalas",
    variant: "Garam Masala",
    packSize: "100g Box",
    unit: "box",
    barcode: "8901786101046",
    mrp: 88,
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80",
    description: "Signature blend of 13 aromatic roasted whole spices including clove and cardamom.",
  },
  {
    productId: "CAT-SPI-006",
    name: "MDH Kitchen King Masala",
    brand: "MDH",
    categoryId: "spices-masalas",
    category: "Spices & Masalas",
    variant: "Kitchen King",
    packSize: "100g Box",
    unit: "box",
    barcode: "8901082001018",
    mrp: 82,
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80",
    description: "The classic all-rounder curry masala blend for paneer, dal and mixed vegetable dishes.",
  },
  {
    productId: "CAT-SPI-007",
    name: "Catch Cumin Seeds Whole (Jeera)",
    brand: "Catch",
    categoryId: "spices-masalas",
    category: "Spices & Masalas",
    variant: "Whole Jeera",
    packSize: "100g Pouch",
    unit: "packet",
    barcode: "8901192001012",
    mrp: 75,
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80",
    description: "Selected aromatic whole cumin seeds for tempering dals, curries, and rice.",
  },

  // ==========================================
  // 9. TEA & COFFEE (CAT-TEA)
  // ==========================================
  {
    productId: "CAT-TEA-001",
    name: "Tata Tea Premium Desh Ki Chai",
    brand: "Tata Tea",
    categoryId: "tea-coffee",
    category: "Tea & Coffee",
    variant: "Leaf & Dust Blend",
    packSize: "500g Pouch",
    unit: "packet",
    barcode: "8901042111018",
    mrp: 230,
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80",
    description: "Unique blend of big tea leaves for great aroma and small grains for rich taste.",
  },
  {
    productId: "CAT-TEA-002",
    name: "Tata Tea Gold Fine CTC Leaves",
    brand: "Tata Tea",
    categoryId: "tea-coffee",
    category: "Tea & Coffee",
    variant: "Gold Tea",
    packSize: "500g Pouch",
    unit: "packet",
    barcode: "8901042111025",
    mrp: 310,
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80",
    description: "Gentle rolled long leaf tea combined with rich Assam CTC for intense aroma.",
  },
  {
    productId: "CAT-TEA-003",
    name: "Red Label Strong CTC Tea",
    brand: "Brooke Bond",
    categoryId: "tea-coffee",
    category: "Tea & Coffee",
    variant: "Nature Care",
    packSize: "500g Pouch",
    unit: "packet",
    barcode: "8901030011019",
    mrp: 260,
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80",
    description: "Infused with 5 ayurvedic ingredients: tulsi, ashwagandha, mulethi, ginger & cardamom.",
  },
  {
    productId: "CAT-TEA-004",
    name: "Nescafe Classic Instant Coffee Jar",
    brand: "Nescafe",
    categoryId: "tea-coffee",
    category: "Tea & Coffee",
    variant: "100% Pure Instant",
    packSize: "100g Glass Jar",
    unit: "jar",
    barcode: "8901058861010",
    mrp: 380,
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80",
    description: "Rich roasted coffee granules giving unmistakable awakening coffee aroma.",
  },
  {
    productId: "CAT-TEA-005",
    name: "Bru Instant Coffee Chicory Mix Pouch",
    brand: "Bru",
    categoryId: "tea-coffee",
    category: "Tea & Coffee",
    variant: "Instant Coffee-Chicory",
    packSize: "100g Pouch",
    unit: "packet",
    barcode: "8901030021018",
    mrp: 180,
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80",
    description: "70% coffee and 30% chicory blend for strong and frothy South Indian style coffee.",
  },

  // ==========================================
  // 10. DAIRY PRODUCTS (CAT-DAI)
  // ==========================================
  {
    productId: "CAT-DAI-001",
    name: "Amul Taaza Homogenised Toned Milk",
    brand: "Amul",
    categoryId: "dairy-products",
    category: "Dairy Products",
    variant: "Toned Milk (3% Fat)",
    packSize: "1 Litre Tetra Pak",
    unit: "tetra",
    barcode: "8901262020106",
    mrp: 75,
    imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80",
    description: "Long life UHT homogenised toned milk, no boiling required before consumption.",
  },
  {
    productId: "CAT-DAI-002",
    name: "Amul Gold Full Cream Milk Pouch",
    brand: "Amul",
    categoryId: "dairy-products",
    category: "Dairy Products",
    variant: "Full Cream (6% Fat)",
    packSize: "500ml Pouch",
    unit: "pouch",
    barcode: "8901262020113",
    mrp: 34,
    imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80",
    description: "Rich and wholesome full cream milk for tea, coffee, desserts and curd.",
  },
  {
    productId: "CAT-DAI-003",
    name: "Amul Pasteurized Salted Butter",
    brand: "Amul",
    categoryId: "dairy-products",
    category: "Dairy Products",
    variant: "Salted Table Butter",
    packSize: "100g Pack",
    unit: "piece",
    barcode: "8901262030105",
    mrp: 58,
    imageUrl: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&auto=format&fit=crop&q=80",
    description: "Utterly Butterly Delicious table butter made with pure cow and buffalo cream.",
  },
  {
    productId: "CAT-DAI-004",
    name: "Amul Pasteurized Butter 500g",
    brand: "Amul",
    categoryId: "dairy-products",
    category: "Dairy Products",
    variant: "Salted Table Butter",
    packSize: "500g Block",
    unit: "piece",
    barcode: "8901262030112",
    mrp: 275,
    imageUrl: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&auto=format&fit=crop&q=80",
    description: "Large 500g family block of Amul pasteurized salted table butter.",
  },
  {
    productId: "CAT-DAI-005",
    name: "Amul Processed Cheese Slices",
    brand: "Amul",
    categoryId: "dairy-products",
    category: "Dairy Products",
    variant: "Processed Cheese",
    packSize: "200g (10 Slices)",
    unit: "packet",
    barcode: "8901262040104",
    mrp: 145,
    imageUrl: "https://images.unsplash.com/photo-1618060932014-4deda4932554?w=500&auto=format&fit=crop&q=80",
    description: "Individually wrapped creamy processed cheddar cheese slices for sandwiches.",
  },
  {
    productId: "CAT-DAI-006",
    name: "Amul Fresh Malai Paneer Block",
    brand: "Amul",
    categoryId: "dairy-products",
    category: "Dairy Products",
    variant: "Malai Paneer",
    packSize: "200g Pack",
    unit: "packet",
    barcode: "8901262050103",
    mrp: 90,
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&auto=format&fit=crop&q=80",
    description: "Soft and spongy traditional cottage cheese cube block for delicious curry cooking.",
  },
  {
    productId: "CAT-DAI-007",
    name: "Amul Masti Dahi Curd Tub",
    brand: "Amul",
    categoryId: "dairy-products",
    category: "Dairy Products",
    variant: "Set Dahi",
    packSize: "400g Tub",
    unit: "tub",
    barcode: "8901262060102",
    mrp: 40,
    imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80",
    description: "Thick, creamy set yogurt packed with natural probiotics.",
  },

  // ==========================================
  // 11. BEVERAGES & JUICES (CAT-BEV)
  // ==========================================
  {
    productId: "CAT-BEV-001",
    name: "Coca-Cola Original Taste Bottle",
    brand: "Coca-Cola",
    categoryId: "beverages-juices",
    category: "Beverages & Juices",
    variant: "Original Taste",
    packSize: "750ml PET",
    unit: "bottle",
    barcode: "8901764012015",
    mrp: 40,
    imageUrl: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop&q=80",
    description: "Sparkling carbonated soft drink with timeless refreshing cola taste.",
  },
  {
    productId: "CAT-BEV-002",
    name: "Thums Up Charged Carbonated Drink",
    brand: "Thums Up",
    categoryId: "beverages-juices",
    category: "Beverages & Juices",
    variant: "Strong Taste",
    packSize: "750ml PET",
    unit: "bottle",
    barcode: "8901764012022",
    mrp: 40,
    imageUrl: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop&q=80",
    description: "India's favourite bold and fizzy cola with an intense spicy kick.",
  },
  {
    productId: "CAT-BEV-003",
    name: "Sprite Lemon-Lime Soft Drink",
    brand: "Sprite",
    categoryId: "beverages-juices",
    category: "Beverages & Juices",
    variant: "Lemon-Lime",
    packSize: "750ml PET",
    unit: "bottle",
    barcode: "8901764012039",
    mrp: 40,
    imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
    description: "Crisp and clear lemon lime carbonated beverage with zero caffeine.",
  },
  {
    productId: "CAT-BEV-004",
    name: "Bisleri Packaged Drinking Water",
    brand: "Bisleri",
    categoryId: "beverages-juices",
    category: "Beverages & Juices",
    variant: "Added Minerals",
    packSize: "1 Litre Bottle",
    unit: "bottle",
    barcode: "8906017290014",
    mrp: 20,
    imageUrl: "https://images.unsplash.com/photo-1560023907-5f339617ea30?w=500&auto=format&fit=crop&q=80",
    description: "10-stage purified mineral drinking water with added potassium and magnesium.",
  },
  {
    productId: "CAT-BEV-005",
    name: "Maaza Mango Drink",
    brand: "Maaza",
    categoryId: "beverages-juices",
    category: "Beverages & Juices",
    variant: "Alphonso Pulp",
    packSize: "600ml Bottle",
    unit: "bottle",
    barcode: "8901764022014",
    mrp: 38,
    imageUrl: "https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=80",
    description: "Thick and luscious mango drink made from pure handpicked Alphonso mango pulp.",
  },
  {
    productId: "CAT-BEV-006",
    name: "Real Fruit Power Mixed Fruit Juice",
    brand: "Real",
    categoryId: "beverages-juices",
    category: "Beverages & Juices",
    variant: "Mixed Fruit",
    packSize: "1 Litre Tetra Pak",
    unit: "tetra",
    barcode: "8901207011019",
    mrp: 130,
    imageUrl: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=500&auto=format&fit=crop&q=80",
    description: "Refreshing nectar juice containing 9 nutritious fruits with no added preservatives.",
  },
  {
    productId: "CAT-BEV-007",
    name: "Red Bull Energy Drink Can",
    brand: "Red Bull",
    categoryId: "beverages-juices",
    category: "Beverages & Juices",
    variant: "Energy Drink",
    packSize: "250ml Can",
    unit: "can",
    barcode: "9002490100070",
    mrp: 125,
    imageUrl: "https://images.unsplash.com/photo-1622543925917-763c34d1a86e?w=500&auto=format&fit=crop&q=80",
    description: "Vitalizes body and mind with premium caffeine, taurine and B-group vitamins.",
  },

  // ==========================================
  // 12. BREAD & BAKERY (CAT-BRE)
  // ==========================================
  {
    productId: "CAT-BRE-001",
    name: "Britannia Daily Fresh White Bread",
    brand: "Britannia",
    categoryId: "bread-bakery",
    category: "Bread & Bakery",
    variant: "White Sandwich Bread",
    packSize: "400g Loaf",
    unit: "packet",
    barcode: "8901063210018",
    mrp: 45,
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80",
    description: "Soft, spongy sliced sandwich white bread baked fresh daily.",
  },
  {
    productId: "CAT-BRE-002",
    name: "Britannia 100% Whole Wheat Brown Bread",
    brand: "Britannia",
    categoryId: "bread-bakery",
    category: "Bread & Bakery",
    variant: "Whole Wheat",
    packSize: "400g Loaf",
    unit: "packet",
    barcode: "8901063210025",
    mrp: 55,
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80",
    description: "Nutritious whole wheat brown bread loaded with natural bran fiber.",
  },
  {
    productId: "CAT-BRE-003",
    name: "Britannia Toastea Premium Wheat Rusk",
    brand: "Britannia",
    categoryId: "bread-bakery",
    category: "Bread & Bakery",
    variant: "Elaichi Rusk",
    packSize: "273g",
    unit: "packet",
    barcode: "8901063220017",
    mrp: 45,
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80",
    description: "Crispy double-baked tea toast enriched with aromatic green cardamom.",
  },
  {
    productId: "CAT-BRE-004",
    name: "Britannia Fruit Cake Bar",
    brand: "Britannia",
    categoryId: "bread-bakery",
    category: "Bread & Bakery",
    variant: "Mix Fruit Cake",
    packSize: "120g",
    unit: "packet",
    barcode: "8901063230016",
    mrp: 30,
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop&q=80",
    description: "Soft sponge cake packed with tutti-frutti and candied fruit bits.",
  },

  // ==========================================
  // 13. PERSONAL CARE (CAT-PER)
  // ==========================================
  {
    productId: "CAT-PER-001",
    name: "Dettol Original Germ Protection Bathing Soap",
    brand: "Dettol",
    categoryId: "personal-care",
    category: "Personal Care",
    variant: "Original Pine",
    packSize: "125g (Pack of 3)",
    unit: "packet",
    barcode: "8901396001019",
    mrp: 135,
    imageUrl: "https://images.unsplash.com/photo-1607006310486-068ce2009ce4?w=500&auto=format&fit=crop&q=80",
    description: "Trusted germ protection bar soap with pine fragrance for everyday family health.",
  },
  {
    productId: "CAT-PER-002",
    name: "Lifebuoy Total 10 Germ Protection Soap",
    brand: "Lifebuoy",
    categoryId: "personal-care",
    category: "Personal Care",
    variant: "Total 10",
    packSize: "125g (Pack of 4)",
    unit: "packet",
    barcode: "8901030031017",
    mrp: 140,
    imageUrl: "https://images.unsplash.com/photo-1607006310486-068ce2009ce4?w=500&auto=format&fit=crop&q=80",
    description: "Formulated with Activ Silver+ formula to protect against 10 infection-causing germs.",
  },
  {
    productId: "CAT-PER-003",
    name: "Dove Cream Beauty Bathing Bar",
    brand: "Dove",
    categoryId: "personal-care",
    category: "Personal Care",
    variant: "1/4th Moisturising Cream",
    packSize: "100g Bar",
    unit: "piece",
    barcode: "8901030032014",
    mrp: 65,
    imageUrl: "https://images.unsplash.com/photo-1607006310486-068ce2009ce4?w=500&auto=format&fit=crop&q=80",
    description: "Enriched with 1/4 moisturising cream for softer, smoother and radiant skin.",
  },
  {
    productId: "CAT-PER-004",
    name: "Colgate Strong Teeth Dental Cream Toothpaste",
    brand: "Colgate",
    categoryId: "personal-care",
    category: "Personal Care",
    variant: "Strong Teeth Amino Shakti",
    packSize: "200g Saver Tube",
    unit: "piece",
    barcode: "8901314011019",
    mrp: 110,
    imageUrl: "https://images.unsplash.com/photo-1559591937-e10321390466?w=500&auto=format&fit=crop&q=80",
    description: "India's #1 dental cream featuring Calcium Boost and Amino Shakti formula.",
  },
  {
    productId: "CAT-PER-005",
    name: "Close Up Ever Fresh Red Hot Gel Toothpaste",
    brand: "Close Up",
    categoryId: "personal-care",
    category: "Personal Care",
    variant: "Red Hot Gel",
    packSize: "150g Tube",
    unit: "piece",
    barcode: "8901030041016",
    mrp: 95,
    imageUrl: "https://images.unsplash.com/photo-1559591937-e10321390466?w=500&auto=format&fit=crop&q=80",
    description: "Antibacterial zinc mouthwash gel for up to 12 hours of fresh breath confidence.",
  },
  {
    productId: "CAT-PER-006",
    name: "Head & Shoulders Anti-Dandruff Shampoo Cool Menthol",
    brand: "Head & Shoulders",
    categoryId: "personal-care",
    category: "Personal Care",
    variant: "Cool Menthol",
    packSize: "180ml Bottle",
    unit: "bottle",
    barcode: "4902430731018",
    mrp: 199,
    imageUrl: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=500&auto=format&fit=crop&q=80",
    description: "Icy cooling menthol formula that removes up to 100% visible dandruff flakes.",
  },
  {
    productId: "CAT-PER-007",
    name: "Clinic Plus Strong & Long Health Shampoo",
    brand: "Clinic Plus",
    categoryId: "personal-care",
    category: "Personal Care",
    variant: "Strong & Long Milk Protein",
    packSize: "175ml Bottle",
    unit: "bottle",
    barcode: "8901030051015",
    mrp: 120,
    imageUrl: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=500&auto=format&fit=crop&q=80",
    description: "Infused with nourishing milk protein formula to strengthen hair from roots.",
  },
  {
    productId: "CAT-PER-008",
    name: "Parachute 100% Pure Coconut Hair Oil",
    brand: "Parachute",
    categoryId: "personal-care",
    category: "Personal Care",
    variant: "100% Pure Coconut",
    packSize: "200ml Bottle",
    unit: "bottle",
    barcode: "8901088021017",
    mrp: 90,
    imageUrl: "https://images.unsplash.com/photo-1608248597359-261546726915?w=500&auto=format&fit=crop&q=80",
    description: "Premium edible grade pure coconut oil filtered through 5-stage purification.",
  },

  // ==========================================
  // 14. HOME CLEANING (CAT-HOM)
  // ==========================================
  {
    productId: "CAT-HOM-001",
    name: "Surf Excel Easy Wash Detergent Powder",
    brand: "Surf Excel",
    categoryId: "home-cleaning",
    category: "Home Cleaning",
    variant: "Easy Wash",
    packSize: "1kg Poly Pack",
    unit: "packet",
    barcode: "8901030061014",
    mrp: 145,
    imageUrl: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=500&auto=format&fit=crop&q=80",
    description: "Super fine detergent powder that removes tough stains like mud and grease effortlessly.",
  },
  {
    productId: "CAT-HOM-002",
    name: "Surf Excel Quick Wash Detergent Powder 2kg",
    brand: "Surf Excel",
    categoryId: "home-cleaning",
    category: "Home Cleaning",
    variant: "Quick Wash",
    packSize: "2kg Poly Pack",
    unit: "packet",
    barcode: "8901030061021",
    mrp: 290,
    imageUrl: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=500&auto=format&fit=crop&q=80",
    description: "Dual enzyme power detergent for quick and spotless fabric washing.",
  },
  {
    productId: "CAT-HOM-003",
    name: "Rin Advanced Detergent Bar",
    brand: "Rin",
    categoryId: "home-cleaning",
    category: "Home Cleaning",
    variant: "Bright Clean",
    packSize: "250g (Pack of 4)",
    unit: "packet",
    barcode: "8901030062011",
    mrp: 75,
    imageUrl: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=500&auto=format&fit=crop&q=80",
    description: "Bar soap with bright clean technology delivering dazzling white clothes.",
  },
  {
    productId: "CAT-HOM-004",
    name: "Vim Lemon Dishwash Gel Bottle",
    brand: "Vim",
    categoryId: "home-cleaning",
    category: "Home Cleaning",
    variant: "Lemon Power",
    packSize: "500ml Bottle",
    unit: "bottle",
    barcode: "8901030063018",
    mrp: 110,
    imageUrl: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=500&auto=format&fit=crop&q=80",
    description: "Concentrated gel infused with real lemon extracts that cuts through burnt grease.",
  },
  {
    productId: "CAT-HOM-005",
    name: "Vim Dishwash Bar with Polycoat",
    brand: "Vim",
    categoryId: "home-cleaning",
    category: "Home Cleaning",
    variant: "Lemon Anti-Sogginess",
    packSize: "300g Bar",
    unit: "piece",
    barcode: "8901030063025",
    mrp: 30,
    imageUrl: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=500&auto=format&fit=crop&q=80",
    description: "Polycoat wrapped bar that lasts longer and resists water sogginess.",
  },
  {
    productId: "CAT-HOM-006",
    name: "Harpic Power Plus Disinfectant Toilet Cleaner",
    brand: "Harpic",
    categoryId: "home-cleaning",
    category: "Home Cleaning",
    variant: "Original Blue",
    packSize: "1 Litre Bottle",
    unit: "bottle",
    barcode: "8901396011018",
    mrp: 199,
    imageUrl: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=500&auto=format&fit=crop&q=80",
    description: "10x better stain removal formula that eliminates 99.9% germs and lime scale.",
  },
  {
    productId: "CAT-HOM-007",
    name: "Lizol Disinfectant Surface & Floor Cleaner",
    brand: "Lizol",
    categoryId: "home-cleaning",
    category: "Home Cleaning",
    variant: "Citrus Fragrance",
    packSize: "1 Litre Bottle",
    unit: "bottle",
    barcode: "8901396012015",
    mrp: 195,
    imageUrl: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=500&auto=format&fit=crop&q=80",
    description: "Kills 99.9% germs while leaving a long-lasting sparkling shine and citrus aroma.",
  },

  // ==========================================
  // 15. PACKAGED FOODS (CAT-PAC)
  // ==========================================
  {
    productId: "CAT-PAC-001",
    name: "Kissan Fresh Tomato Ketchup Bottle",
    brand: "Kissan",
    categoryId: "packaged-foods",
    category: "Packaged Foods",
    variant: "100% Real Tomatoes",
    packSize: "950g Squeezy Bottle",
    unit: "bottle",
    barcode: "8901030071013",
    mrp: 135,
    imageUrl: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500&auto=format&fit=crop&q=80",
    description: "Tangy and thick sauce crafted from 100% ripe Indian farm tomatoes.",
  },
  {
    productId: "CAT-PAC-002",
    name: "Kissan Mixed Fruit Jam Glass Jar",
    brand: "Kissan",
    categoryId: "packaged-foods",
    category: "Packaged Foods",
    variant: "8 Real Fruit Pulp",
    packSize: "500g Jar",
    unit: "jar",
    barcode: "8901030072010",
    mrp: 170,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80",
    description: "Delicious breakfast fruit spread made with apples, papayas, mangoes and bananas.",
  },
  {
    productId: "CAT-PAC-003",
    name: "Dabur 100% Pure Honey Squeezy Pack",
    brand: "Dabur",
    categoryId: "packaged-foods",
    category: "Packaged Foods",
    variant: "Pure Wildflower Honey",
    packSize: "400g Squeezy Bottle",
    unit: "bottle",
    barcode: "8901207021018",
    mrp: 199,
    imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&auto=format&fit=crop&q=80",
    description: "NMR tested 100% pure honey free from sugar adulteration, rich in immunity.",
  },
  {
    productId: "CAT-PAC-004",
    name: "Kellogg's Corn Flakes Original",
    brand: "Kellogg's",
    categoryId: "packaged-foods",
    category: "Packaged Foods",
    variant: "Original Crispy Flakes",
    packSize: "475g Carton",
    unit: "box",
    barcode: "8901499011015",
    mrp: 185,
    imageUrl: "https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?w=500&auto=format&fit=crop&q=80",
    description: "Golden sun-ripened corn flakes enriched with iron and 8 essential vitamins.",
  },
  {
    productId: "CAT-PAC-005",
    name: "Quaker Rolled Oats Whole Grain",
    brand: "Quaker",
    categoryId: "packaged-foods",
    category: "Packaged Foods",
    variant: "100% Whole Grain",
    packSize: "1kg Pouch",
    unit: "packet",
    barcode: "8901491121019",
    mrp: 199,
    imageUrl: "https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?w=500&auto=format&fit=crop&q=80",
    description: "Beta-glucan rich whole grain oats for heart health, stamina and weight control.",
  },

  // ==========================================
  // 16. BABY CARE (CAT-BAB)
  // ==========================================
  {
    productId: "CAT-BAB-001",
    name: "Pampers All Round Protection Baby Diaper Pants M",
    brand: "Pampers",
    categoryId: "baby-care",
    category: "Baby Care",
    variant: "Medium (7-12 kg)",
    packSize: "36 Diaper Pants",
    unit: "packet",
    barcode: "4987176011014",
    mrp: 499,
    imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80",
    description: "Magic gel technology with aloe vera lotion for up to 12 hours of dry leak protection.",
  },
  {
    productId: "CAT-BAB-002",
    name: "Huggies Wonder Pants Baby Diaper Pants L",
    brand: "Huggies",
    categoryId: "baby-care",
    category: "Baby Care",
    variant: "Large (9-14 kg)",
    packSize: "34 Diaper Pants",
    unit: "packet",
    barcode: "8902785011019",
    mrp: 479,
    imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80",
    description: "Bubble bed soft breathable elastic waistband with up to 12 hours overnight absorption.",
  },
  {
    productId: "CAT-BAB-003",
    name: "Johnson's Baby Gentle Cleansing Soap",
    brand: "Johnson's Baby",
    categoryId: "baby-care",
    category: "Baby Care",
    variant: "No More Tears",
    packSize: "100g Bar",
    unit: "piece",
    barcode: "8901012111019",
    mrp: 75,
    imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80",
    description: "Hypoallergenic mild baby soap with 1/4 baby lotion for gentle infant skin.",
  },
  {
    productId: "CAT-BAB-004",
    name: "Himalaya Gentle Baby Wipes with Aloe & Lotus",
    brand: "Himalaya",
    categoryId: "baby-care",
    category: "Baby Care",
    variant: "Aloe & Indian Lotus",
    packSize: "72 Wet Wipes",
    unit: "packet",
    barcode: "8901138811019",
    mrp: 190,
    imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80",
    description: "Alcohol and paraben-free soothing wet cleansing wipes for delicate baby skin.",
  },

  // ==========================================
  // 17. STATIONERY (CAT-STA)
  // ==========================================
  {
    productId: "CAT-STA-001",
    name: "Classmate Soft Cover Notebook Single Line",
    brand: "Classmate",
    categoryId: "stationery",
    category: "Stationery",
    variant: "Single Line (Ruled)",
    packSize: "172 Pages (Pack of 4)",
    unit: "packet",
    barcode: "8901725141010",
    mrp: 180,
    imageUrl: "https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=500&auto=format&fit=crop&q=80",
    description: "Chlorine-free ozone bleached super white paper with activity puzzles.",
  },
  {
    productId: "CAT-STA-002",
    name: "Reynolds 045 Fine Carbure Ball Pen Blue",
    brand: "Reynolds",
    categoryId: "stationery",
    category: "Stationery",
    variant: "Blue Ink 0.7mm",
    packSize: "Pack of 5 Pens",
    unit: "packet",
    barcode: "8901185011011",
    mrp: 50,
    imageUrl: "https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=500&auto=format&fit=crop&q=80",
    description: "Classic hexagonal body ball pen delivering consistent smooth non-smudge writing.",
  },
  {
    productId: "CAT-STA-003",
    name: "Apsara Platinum Extra Dark Pencils",
    brand: "Apsara",
    categoryId: "stationery",
    category: "Stationery",
    variant: "Extra Dark Lead",
    packSize: "Pack of 10 with Eraser & Sharpener",
    unit: "box",
    barcode: "8901324011016",
    mrp: 60,
    imageUrl: "https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=500&auto=format&fit=crop&q=80",
    description: "Super soft bonded lead pencils producing distinct bold black writing without breakage.",
  },
  {
    productId: "CAT-STA-004",
    name: "Fevicol MR Squeezy Craft Adhesive",
    brand: "Pidilite Fevicol",
    categoryId: "stationery",
    category: "Stationery",
    variant: "White Adhesive Glue",
    packSize: "100g Bottle",
    unit: "bottle",
    barcode: "8901860011019",
    mrp: 45,
    imageUrl: "https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=500&auto=format&fit=crop&q=80",
    description: "Non-staining synthetic white adhesive for paper, cardboard, craft and hobby bonding.",
  },

  // ==========================================
  // 18. OTHER / LOCAL PRODUCTS (CAT-OTH)
  // ==========================================
  {
    productId: "CAT-OTH-001",
    name: "Local Kirana Traditional Makhana (Fox Nuts)",
    brand: "Local Provisions",
    categoryId: "other-local-products",
    category: "Other / Local Products",
    variant: "Graded Jumbo",
    packSize: "200g Pouch",
    unit: "packet",
    barcode: "",
    mrp: 220,
    imageUrl: "https://images.unsplash.com/photo-1599785209707-a456fc1337bb?w=500&auto=format&fit=crop&q=80",
    description: "Natural handpicked puffed lotus seeds, high in calcium and low in calories.",
  },
  {
    productId: "CAT-OTH-002",
    name: "Artisanal Organic Desi Jaggery Cubes (Gud)",
    brand: "Local Farms",
    categoryId: "other-local-products",
    category: "Other / Local Products",
    variant: "Natural Desi Gud",
    packSize: "1kg Block",
    unit: "packet",
    barcode: "",
    mrp: 90,
    imageUrl: "https://images.unsplash.com/photo-1599785209707-a456fc1337bb?w=500&auto=format&fit=crop&q=80",
    description: "Unrefined mineral rich golden brown sugarcane jaggery cubes, free from chemicals.",
  },
  {
    productId: "CAT-OTH-003",
    name: "Local Fresh Bakery Nankhatai Biscuits",
    brand: "Local Bakery",
    categoryId: "other-local-products",
    category: "Other / Local Products",
    variant: "Cardamom Pistachio",
    packSize: "300g Box",
    unit: "box",
    barcode: "",
    mrp: 120,
    imageUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=500&auto=format&fit=crop&q=80",
    description: "Melt-in-mouth traditional Indian shortbread baked fresh by local neighbourhood bakeries.",
  },
  {
    productId: "CAT-OTH-004",
    name: "Traditional Mango Pickle in Mustard Oil",
    brand: "Local Homemade",
    categoryId: "other-local-products",
    category: "Other / Local Products",
    variant: "Spicy Aam Ka Achaar",
    packSize: "500g Glass Jar",
    unit: "jar",
    barcode: "",
    mrp: 160,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80",
    description: "Homestyle sun-dried raw mango pickle marinated with fennel, nigella seeds and mustard oil.",
  },
];
